spring:
  version: 0.1
  application:
    name: risk-project
  config:
    import: "optional:configserver:http://localhost:8088"
  mail:
    host: smtp.gmail.com
    port: 587
    username: riskemailtests@gmail.com
    password: riskriskrisk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#OpenApi configurations
springdoc:
  pathsToMatch: /api/**
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha

#Swagger configurations
swagger:
  title: ${spring.application.name} API
  description: ${spring.application.name} API documentation
  version: ${application.version}
  terms-of-service-url:
  contact-name:
  contact-url:
  contact-email:
  license:
  license-url:
  external-documentation:
  external-documentation-url:

#api.key : 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
api.key : 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


